---

- hosts: all
  become: true
  tasks: 

  - name: Collection of log files
    find:
      paths: /var/log/
      patterns: '*.log"
    register: log_files



 - name: Copy of Log files
    fetch:
      src: "{{ item.path }}"
      dest: /tmp/logs/
      flat: yes
    with_items: "{{ log_files.files }}"

